theme = "nostyleplease"
baseURL = 'https://gh-shinku.github.io/'
languageCode = 'zh-cn'
title = "shinku's blog"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    noClasses = false
    style = "friendly"
    tabWidth = 4
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  favicon = "favicon.ico"
  toc = true
  tocBorder = true